apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        stats socket /tmp/haproxy.sock mode 660 level admin
    
    defaults
        log     global
        mode    tcp
        option  tcplog
        timeout connect 5s
        timeout client  30m
        timeout server  30m

    resolvers k8s
        parse-resolv-conf
        resolve_retries 3
        timeout resolve 1s
        timeout retry 1s
        hold other 10s
        hold refused 10s
        hold nx 10s
        hold timeout 10s
        hold valid 5s
        hold obsolete 10s
    
    # External entrypoint for NestJS writes
    frontend postgres_write_front
        bind *:5432
        default_backend postgres_write_back
    
    backend postgres_write_back
        default-server init-addr last,libc,none
        server pgbouncer_primary_srv pgbouncer-primary.default.svc.cluster.local:6432 check resolvers k8s resolve-prefer ipv4
    
    # External entrypoint for NestJS reads
    frontend postgres_read_front
        bind *:5433
        default_backend postgres_read_back
    
    backend postgres_read_back
        default-server init-addr last,libc,none
        server pgbouncer_replica_srv pgbouncer-replica.default.svc.cluster.local:6432 check resolvers k8s resolve-prefer ipv4
    
    # Internal dynamic routing for Primary Database (Writes)
    frontend patroni_primary_front
        bind *:5000
        default_backend patroni_primary_back
    
    backend patroni_primary_back
        option httpchk GET /primary
        http-check expect status 200
        default-server init-addr last,libc,none inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
        server pg-primary pg-primary.default.svc.cluster.local:5432 check port 8008 resolvers k8s resolve-prefer ipv4
        server pg-replica pg-replica.default.svc.cluster.local:5432 check port 8008 resolvers k8s resolve-prefer ipv4
    
    # Internal dynamic routing for Replica Databases (Reads)
    frontend patroni_replica_front
        bind *:5001
        default_backend patroni_replica_back
    
    backend patroni_replica_back
        balance roundrobin
        option httpchk GET /replica
        http-check expect status 200
        default-server init-addr last,libc,none inter 3s fall 3 rise 2
        server pg-primary pg-primary.default.svc.cluster.local:5432 check port 8008 resolvers k8s resolve-prefer ipv4
        server pg-replica pg-replica.default.svc.cluster.local:5432 check port 8008 resolvers k8s resolve-prefer ipv4
    
    # NestJS HTTP Application Load Balancer
    frontend nest_app_front
        bind *:3000
        mode http
        default_backend nest_app_back
    
    backend nest_app_back
        mode http
        balance roundrobin
        default-server init-addr last,libc,none
        server-template nest_app_template 1-10 nestapp.default.svc.cluster.local:3000 check resolvers k8s resolve-prefer ipv4
    
    # Go Gin HTTP Application Load Balancer
    frontend go_app_front
        bind *:8080
        mode http
        default_backend go_app_back
    
    backend go_app_back
        mode http
        balance roundrobin
        default-server init-addr last,libc,none
        server-template go_app_template 1-10 goapp.default.svc.cluster.local:8080 check resolvers k8s resolve-prefer ipv4
